services:
  mysql:
    image: mysql:8.4
    container_name: portfolio-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: portfolio_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - portfolio_mysql_data:/var/lib/mysql

volumes:
  portfolio_mysql_data:
